---
# Dict for category names:
title:
  '0': "Last Torrent"
  '1': "Categorie Vidéo"
  '2': "Categorie Audio"
  '3': "Categorie Application"
  '4': "Categorie Ebooks"
  '5': "Categorie Jeu-Vidéo"
  '6': "Categorie Formation"
  '7': "Categorie XXX"
  '9': "SubCategorie Film"
  '10': "SubCategorie Série"
  '11': "SubCategorie Film Animation"
  '12': "SubCategorie Série Animation"
  '13': "SubCategorie Documentaire"
  '14': "SubCategorie Emission TV"
  '15': "SubCategorie Spectacle & Concert"
  '16': "SubCategorie Sport"
  '17': "SubCategorie Karaoké Vidéo"
  '18': "SubCategorie Karaoké"
  '19': "On The Cloud"
  '20': "SubCategorie Musique"
  '21': "SubCategorie Podcast"
  '22': "SubCategorie Sample"
  '23': "SubCategorie Ebook Audio"
  '24': "SubCategorie BD"
  '25': "SubCategorie Comic"
  '26': "SubCategorie Manga"
  '27': "SubCategorie Livre"
  '28': "SubCategorie Presse"
  '29': "SubCategorie Application Linux"
  '30': "SubCategorie Application Windows"
  '31': "SubCategorie Application Mac"
  '32': "On The Cloud"
  '33': "On The Cloud"
  '34': "SubCategorie Application Smartphone/Tablette"
  '35': "SubCategorie GPS"
  '36': "SubCategorie Jeux Linux"
