---
services:
  sharewood:
    container_name: sharewood
    image: corentinrhr/sharewood-rss
    restart: unless-stopped
    ports:
      - '14000:14000'
    environment:
      # Optionnel
      - RSS_USERNAME=${RSS_USERNAME}
      - RSS_PASSWORD=${RSS_PASSWORD}