---
services:
  sharewood:
    container_name: sharewood
    image: corentinrhr/sharewood-rss
    restart: unless-stopped
    ports:
      - '14000:14000'
    environment:
      # Laisser vide pour d√©sactiver l'authentification
      - RSS_USERNAME=
      - RSS_PASSWORD=
